### ISSUE TITLE
Publish Docker image to GitHub repository and/or Docker Hub

### ISSUE THREAD

**Issue by jimisola** [unoconv/unoserver-docker#2]
# Summary

When the Docker image is satisfactory then publish it to the GitHub repository.

See e.g.

1. [Publishing Docker images](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images)
2. https://dev.to/github/publishing-a-docker-image-to-githubs-container-repository-4n50

**Comment by jimisola** [comment]
@regebro Shall we just publish to GitHub Packages or also Docker Hub? If it is the latter then someone of us needs to create an account at Docker Hub. And it needs the ["Open Source Software Project" status](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/).

I personally GitHub Packages is sufficient - at least initially.

**Comment by jimisola** [comment]
@regebro I need more permissions to complete this task as well.

```
docker login ghcr.io
Username: jimisola
Password: 
WARNING! Your password will be stored unencrypted in /home/jimisola/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
jimisola@turing:~/cloud/dev/clones/github/unoconv/unoserver-docker (feature/create_docker_image)$ docker push ghcr.io/unoconv/unoserver-docker:0.1.0-beta
The push refers to repository [ghcr.io/unoconv/unoserver-docker]
357c49e58e8a: Preparing 
0beb6c373949: Preparing 
df7ba8c99eea: Preparing 
a68f53ff4728: Preparing 
d202972c9376: Preparing 
c2db65e77a8c: Waiting 
41573c240793: Waiting 
a1a273a33cc7: Waiting 
597500ab4e75: Waiting 
ded7a220bb05: Waiting 
denied: permission_denied: create_package
```

**Comment by regebro** [comment]
I don't know anything about Docker packages, so I have no opinion.

It seems that to create packages you have to be an organization member, so I sent invites.

**Comment by jimisola** [comment]
@regebro Yes. I could push now, so I pushed 0.1.0-beta manually. This issue is about adding GitHub Actions to automate the deployment.

For some reason Packages is not public and the "Setting is disabled by organization administrators."

I don't have enough privileges to change the settings since I can't access [package settings for this organization](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#container-creation-visibility-for-organization-members) (I think that this would be the [direct link](
https://github.com/organizations/unoconv/settings/packages) comparing with other open source projects that I'm involved in).

Can you activate it or give me permissions to do it? That said, I think there are other settings under "Code, planning, and automation" that needs change as well. Not sure yet though as I'm new to this part of GitHub.

**Comment by regebro** [comment]
OK, you should be able to publish it now.
