### ISSUE TITLE
arm64 images missing since 0.2.0

### ISSUE THREAD

**Issue by jabbrwcky** [unoconv/unoserver-docker#48]
Up to 0.2.0 the image built both an amd64 as well as an arm64 image.

Also all versions since have been missing information form the image:

Compare  https://github.com/unoconv/unoserver-docker/pkgs/container/unoserver-docker/93125136?tag=0.2.0
to https://github.com/unoconv/unoserver-docker/pkgs/container/unoserver-docker/117999979?tag=0.2.1

Nearly all openimage labels have gone missing and the second arch is listed as unkown/unknown

**Comment by jimisola** [comment]
@jabbrwcky First of all, thank you for the bug report. Not sure how this can have gone unnoticed.

Regarding, the amd64 and arm64. To my understanding we only built and published an amd64.
Compare:

0.2.0: https://github.com/unoconv/unoserver-docker/pkgs/container/unoserver-docker/93125136?tag=0.2.0

with

0.2.1: https://github.com/unoconv/unoserver-docker/pkgs/container/unoserver-docker/117999979?tag=0.2.1

where the latter has an "OS / Arch (2)" tab and with OS/Arch:

* linux/amd64
* unknown/unknown

Can you please point me to where you could buklds for arm64 images from 0.2.0 and before?

I'm quite flabbergasted and honestly don't know where things are going wrong. The change to official eclipse-temurin images was not made until 0.3.0.

**Comment by jimisola** [comment]
I reworked the workflow. Not there is a arm64 but no amd64... 

The unknown/unknown seems to be due to https://github.com/orgs/community/discussions/45969

Will look at the lack of two archs when I have the time.

**Comment by jabbrwcky** [comment]
Right now I even get a manifest unknown error:

```shell
❯ docker pull ghcr.io/unoconv/unoserver-docker:0.3.1
0.3.1: Pulling from unoconv/unoserver-docker
manifest unknown

❯ docker pull ghcr.io/unoconv/unoserver-docker:0.3.0
0.3.0: Pulling from unoconv/unoserver-docker
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Quite puzzling. Looking at the actions, everything does look fine. Could it be a registry issue?

**Comment by jimisola** [comment]
I haven't ruled that option out yet.

**Comment by jimisola** [comment]
I fixed so that both amd64 and arm64 are published. However, the About of the package page still lacks the description. I've tried everything that I have found but it could be that because the workflow now uses merge digest into a manifest it must be done in another way.

**Comment by jimisola** [comment]
Solved with release https://github.com/unoconv/unoserver-docker/releases/tag/v0.3.21
