### ISSUE TITLE
sync docker tag with unoserver version

### ISSUE THREAD

**Issue by bschoenmaeckers** [unoconv/unoserver-docker#66]
It is currently not trivial to keep the docker image containing the server and a remote running client in sync. This results in errors like https://github.com/unoconv/unoserver/issues/130 because the client & the server version mismatch. So I propose that the docker tag should be the same as the version of the installed unoserver package within.

**Comment by jimisola** [comment]
This is not feasible since the container image is not only released (and tag) when there is a new version of unoserver but also e.g. new versions of

* Java
* Alpine
