### ISSUE TITLE
Activate renovate bot

### ISSUE THREAD

**Issue by jimisola** [unoconv/unoserver-docker#70]

**Comment by regebro** [comment]
Do you need it for all repositories, or just unoserver-docker? I personally
hate getting these kinds of emails from various bots trying to tell me
things are outdated, when they aren't. :-D

**Comment by regebro** [comment]
I can see that might be a problem for docker images.

**Comment by jimisola** [comment]
Any type of dependency is my experience. Pypi, Maven, NPM. We use renovate for everything at work. Would be able to keep up otherwise.

How do you keep track of unoserver's dependencies?

DevOps Paradox podcast recently had an episode with the founder of renovate:

https://www.devopsparadox.com/episodes/automating-dependency-updates-with-renovate-287/

**Comment by regebro** [comment]
Pypi will install the latest version of any dependency, so that's not a
problem for me, in general. For unoserver, specifically, it doesn't even
have dependencies, so that's even easier. :-D
